"""Install and enable the `frp-jump-server` systemd unit.

Mirrors `agent/service_install.py`'s client-side pattern -- reuses its
generic `ensure_system_user`/`chown_tree`/`resolve_exec_path` helpers
(creating an isolated system account has nothing device-specific about
it), and generates a hardened unit matching this project's own real
deployment (see docs/architecture.md): a dedicated, unprivileged system
account, `ProtectSystem=strict` with a single writable data directory,
config in a separate `EnvironmentFile` the operator can keep editing
without ever touching the generated unit again. Also runs
`bootstrap.initialize` (idempotent) so this is the entire one-shot setup,
not just the unit file.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from frp_jump.agent.service_install import (
    ServiceInstallError,
    chown_tree,
    ensure_system_user,
    resolve_exec_path,
)
from frp_jump.common.settings import Settings
from frp_jump.server import bootstrap

#: Module attributes, not inline literals, so tests can monkeypatch them
#: to a writable directory instead of touching the real system locations.
_SYSTEM_UNIT_DIR = Path("/etc/systemd/system")
_ENV_DIR = Path("/etc/frp-jump")
_ADMIN_WRAPPER_PATH = Path("/usr/local/bin/frp-jump-server")

# The dedicated system account's data dir is 0700 (see bootstrap._ensure_data_dir)
# -- only it, or root, can read the database at all. Without this, "SSH access
# to the box is the admin boundary" (see docs/architecture.md) is only true
# for root: everyone else would need to know to type `sudo -u <system_user>
# env FRP_JUMP_DATA_DIR=<data_dir> <exec_path> ...` by hand for every single
# admin command. This wrapper does that instead, so anyone who can `sudo` on
# this box can just run `frp-jump-server users list` and have it work.
# `install-service`/`init`/`run` are passed straight through unwrapped --
# those need to actually run as root (or under systemd), not the unprivileged
# service account, and don't touch the database directly by themselves before
# checking that.
_ADMIN_WRAPPER_TEMPLATE = """\
#!/bin/sh
# Generated by `frp-jump-server install-service` -- rerun that to refresh
# this after e.g. upgrading the binary.
case "$1" in
    install-service|init|run)
        exec {exec_path} "$@"
        ;;
    *)
        exec sudo -u {system_user} env FRP_JUMP_DATA_DIR={data_dir} {exec_path} "$@"
        ;;
esac
"""

_UNIT_TEMPLATE = """\
[Unit]
Description=frp-jump server (control-plane + relay)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={system_user}
Group={system_user}
EnvironmentFile={env_path}
ExecStart={exec_path} run
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths={data_dir}
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
"""


def _read_env_value(env_path: Path, key: str) -> str | None:
    prefix = f"{key}="
    for line in env_path.read_text().splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :]
    return None


def install(
    *,
    system_user: str = "frp-jump",
    relay_public_addr: str | None = None,
    tls_cert_file: Path | None = None,
    tls_key_file: Path | None = None,
) -> Path:
    """Create (if missing) a dedicated system account, its config file and
    data directory, bootstrap the CA/database in it, and a hardened
    systemd unit -- then `enable --now` it. Returns the unit path.
    Requires root. Safe to rerun (e.g. after upgrading the binary) -- an
    already-existing env file is left alone, so ``relay_public_addr``/
    ``tls_cert_file``/``tls_key_file`` are only used the first time.

    ``server run`` refuses to bind a non-loopback ``api_host`` with no TLS
    configured (see its own docstring) -- so this either writes
    ``tls_cert_file``/``tls_key_file`` into the env file (serving real TLS
    directly), or, if neither is given, defaults to
    ``FRP_JUMP_API_HOST=127.0.0.1`` and expects the operator to front that
    with their own TLS-terminating reverse proxy (this project's own
    production deployment does exactly that). Either way, the service
    starts successfully with no further config needed.
    """
    if os.geteuid() != 0:
        raise ServiceInstallError("installing the service requires root -- rerun with sudo")
    if bool(tls_cert_file) != bool(tls_key_file):
        raise ServiceInstallError("--tls-cert and --tls-key must be given together")

    data_dir = ensure_system_user(system_user)

    env_path = _ENV_DIR / f"{system_user}.env"
    if not env_path.is_file():
        if not relay_public_addr:
            raise ServiceInstallError(
                "--relay-public-addr is required the first time -- the address "
                "other devices will use to reach this server"
            )
        lines = [
            f"FRP_JUMP_DATA_DIR={data_dir}",
            f"FRP_JUMP_RELAY_PUBLIC_ADDR={relay_public_addr}",
        ]
        if tls_cert_file and tls_key_file:
            lines.append(f"FRP_JUMP_TLS_CERT_FILE={tls_cert_file}")
            lines.append(f"FRP_JUMP_TLS_KEY_FILE={tls_key_file}")
        else:
            lines.append("FRP_JUMP_API_HOST=127.0.0.1")
        env_path.parent.mkdir(parents=True, exist_ok=True)
        env_path.write_text("\n".join(lines) + "\n")
        env_path.chmod(0o640)
        shutil.chown(env_path, user=system_user, group=system_user)

    resolved_relay_addr = relay_public_addr or _read_env_value(
        env_path, "FRP_JUMP_RELAY_PUBLIC_ADDR"
    )
    settings = Settings(data_dir=data_dir, relay_public_addr=resolved_relay_addr)
    try:
        bootstrap.initialize(settings)
    except bootstrap.ConfigError as exc:
        raise ServiceInstallError(str(exc)) from exc
    chown_tree(data_dir, system_user)

    exec_path = resolve_exec_path("frp-jump-server")

    _SYSTEM_UNIT_DIR.mkdir(parents=True, exist_ok=True)
    unit_path = _SYSTEM_UNIT_DIR / "frp-jump-server.service"
    unit_path.write_text(
        _UNIT_TEMPLATE.format(
            system_user=system_user,
            env_path=env_path,
            data_dir=data_dir,
            exec_path=exec_path,
        )
    )
    unit_path.chmod(0o644)

    _ADMIN_WRAPPER_PATH.parent.mkdir(parents=True, exist_ok=True)
    _ADMIN_WRAPPER_PATH.write_text(
        _ADMIN_WRAPPER_TEMPLATE.format(
            exec_path=exec_path, system_user=system_user, data_dir=data_dir
        )
    )
    _ADMIN_WRAPPER_PATH.chmod(0o755)

    try:
        subprocess.run(["systemctl", "daemon-reload"], check=True, capture_output=True)
        subprocess.run(
            ["systemctl", "enable", "--now", "frp-jump-server"], check=True, capture_output=True
        )
    except subprocess.CalledProcessError as exc:
        raise ServiceInstallError(
            f"systemctl failed: {exc.stderr.decode(errors='replace').strip()}"
        ) from exc
    except FileNotFoundError as exc:
        raise ServiceInstallError("systemctl not found -- is this a systemd system?") from exc
    return unit_path
